version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ..:/workspace:cached
      - /workspace/node_modules
      - /workspace/services/*/node_modules
      - /workspace/frontend/node_modules
      - /workspace/shared/node_modules
    command: sleep infinity
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/user_management
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=dev-secret-key
      - AUTH_SERVICE_URL=http://localhost:3001
      - USER_SERVICE_URL=http://localhost:3002
      - SESSION_SERVICE_URL=http://localhost:3003
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../migrations:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: user_management
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data: 